# Generated by Django 5.0.6 on 2024-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
